### ISSUE TITLE
Doctype Incorrect

### ISSUE THREAD

**Issue by incognitojam** [Arze1/CSGO-Overpay-Bot#11]
You aren't using the correct doctype. This can cause Google Ultron users to run out of RAM increasingly quickly. You should do this:

`<!HTML doctype>`

Temporary fix [here](http://www.downloadmoreram.com/).

PS. Remember to update Adobe Flash Player!

**Comment by yaneony** [comment]
Having same problem! Please fix! Can't trade!

**Comment by ezraripps** [comment]
Yeah but after I went to that site my anti-virus said it found a wirus, I called the number and paid them, dosnt seem they are picking back up :/

**Comment by ezraripps** [comment]
Also isn't it <LMTH! epycod>

**Comment by ezraripps** [comment]
IE glitched once I went to site. Glad we won the race to space
