### ISSUE TITLE
How do we add api key?

### ISSUE THREAD

**Issue by kotik1998** [Arze1/CSGO-Overpay-Bot#12]
How do we add api key?

and and i'm having error null : status code 401  

the error is probably due to limited account i think..

**Comment by ezraripps** [comment]
Add an api key from the link I sent, it's on readme

**Comment by kotik1998** [comment]
and from that error that i'm having :  error null : status code 401 

![b5d781e582054e73b109149f2d7a3131](https://cloud.githubusercontent.com/assets/23015769/21977385/db6df02a-dbcd-11e6-8636-3715423ecc6b.png)
![66bb21056ba34e32b8f70c6d9263164c](https://cloud.githubusercontent.com/assets/23015769/21977386/db71788a-dbcd-11e6-94ea-445133c5fa1b.png)

**Comment by kotik1998** [comment]
Edit: i used the api key from my alt account and i have this error 
![be9837db473c45cb83600b63139ee750](https://cloud.githubusercontent.com/assets/23015769/21977594/b740f6b0-dbce-11e6-9f38-a8f1888e8bff.png)

i this error Access denied is probably from te limited account ;/ need to deposit 5 € right?

**Comment by ezraripps** [comment]
mhm you should have to, idk tho.

if you want more help add me on steam http://steamcommunity.com/id/Arze_

**Comment by FreddyFish** [comment]
Yes. You need to deposit 5 EUR, and have steam mobile auth activated for 3 weeks (i belive)

**Comment by kotik1998** [comment]
@FreddyFish  ty
@Arze1 i added you if i need any help.

**Comment by kotik1998** [comment]
http://steamcommunity.com/id/kotik_1998 @Arze1 sent you an invite
