### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kotik1998** [Arze1/CSGO-Overpay-Bot#13]
![](http://image.prntscr.com/image/cba33a67ff09460fbc6e6e4d59e3bef7.png)

**Comment by ezraripps** [comment]
Huh

**Comment by ezraripps** [comment]
What's the err

**Comment by kotik1998** [comment]
i put every thing on config, but not working ;/


BTW are you accepting some Ideas to the bot?

**Comment by FreddyFish** [comment]
I belive this is a steam issue.

**Comment by kotik1998** [comment]
@FreddyFish that happend yesterday aswell and it didnt work.

**Comment by ezraripps** [comment]
Steam Is up

**Comment by ezraripps** [comment]
It was working fine before, try using another computer or using a vpn

**Comment by kotik1998** [comment]
when i uploaded the picture, atm i didnt closed the console and it's full of those errors:

![](http://image.prntscr.com/image/b9a93014278b4080b7d87e5361f964d9.png)

**Comment by ezraripps** [comment]
Close the console and try on different ip

**Comment by kotik1998** [comment]
ok il try a vpn, cuz i dont have more computer

**Comment by kotik1998** [comment]
still gettin' the error with a VPN

**Comment by ezraripps** [comment]
Ok, could you tell me what VPN?

**Comment by kotik1998** [comment]
cyberghost

**Comment by ezraripps** [comment]
Web VPN or full program?

**Comment by kotik1998** [comment]
full

**Comment by ezraripps** [comment]
You got this before?

**Comment by ezraripps** [comment]
Error

**Comment by kotik1998** [comment]
yes

**Comment by ezraripps** [comment]
Hmm idk lol, I'll look into it later cuz my wifi is down so I can only use phone

**Comment by FreddyFish** [comment]
It works fine for me.
Not sure what you have done.

Can you upload your bot.js

**Comment by kotik1998** [comment]
;(

**Comment by ezraripps** [comment]
Try to re-dl

**Comment by kotik1998** [comment]
do i need to reinstall node, or update modules?

**Comment by kotik1998** [comment]
@Arze1 i did it twice

**Comment by FreddyFish** [comment]
Try installing latest stable version of node, and run a npm install on a brand new project folder.

**Comment by ezraripps** [comment]
Try all of that but idk why it isn't working

**Comment by kotik1998** [comment]
if it's working for frfeddy and not for me it think something worng with my ndoe i guess...

**Comment by kotik1998** [comment]
il do that freddy

**Comment by ezraripps** [comment]
Yep do what @FreddyFish said

**Comment by FreddyFish** [comment]
Please upload your bot.js and config.js > Remember to edit your account info out.

Pretty sure it could be because of bad API key. 404 is website not found, and it will return null if the api key for steamapi.io is invalid.

**Comment by kotik1998** [comment]
ive got my api key on https://steamcommunity.com/dev/apikey

**Comment by kotik1998** [comment]
i reinstalled node to 7.4 and same error

**Comment by ezraripps** [comment]
Nono use 6.9 and delete the folder for the bot

**Comment by FreddyFish** [comment]
There you have the problem.  API key should not be grabbed from https://steamcommunity.com/dev/apikey

Instead go here:  https://steamapi.io/user
Also stated in the readme.

**Comment by ezraripps** [comment]
Lol great

**Comment by kotik1998** [comment]
6.9 ? 
ok i download 6.9 and use the key from  https://steamapi.io/user

**Comment by ezraripps** [comment]
Thanks

**Comment by FreddyFish** [comment]
Error was not because of node, or your modules.
It was because it could not access steamapi.io with the provided API key.

Do what i said and it should work.

**Comment by kotik1998** [comment]
http://prntscr.com/dyo4xg

**Comment by kotik1998** [comment]
now it works but then i have this

**Comment by ezraripps** [comment]
Dosnt matter

**Comment by kotik1998** [comment]
what is that error?

**Comment by ezraripps** [comment]
Exactly what it says it is

**Comment by kotik1998** [comment]
im really noob ( almost 0 experience with javascript) so i dont know that error.

but i reading this https://github.com/getify/You-Dont-Know-JS to learn javascript

**Comment by kotik1998** [comment]
arze can i add you on steam? 
https://steamcommunity.com/id/kotik_1998/

**Comment by ezraripps** [comment]
https://steamcommunity.com/id/Arze_

**Comment by ezraripps** [comment]
Ok phone so you add me

**Comment by ezraripps** [comment]
On

**Comment by kotik1998** [comment]
sent

**Comment by kotik1998** [comment]
ok, everything is setted up but, the bot seems to accept everything i even lowballed him so bad that he accepted righ away :/
