### ISSUE TITLE
Add Item Filtering

### ISSUE THREAD

**Issue by kotik1998** [Arze1/CSGO-Overpay-Bot#16]
Can you add item filtering/ban, or like denie offers if there item below x ammount.

Just to prevent people to add cases or 3 cent skins to do the over pay.

like 1$+0.03+0.03+0.04 = 1.1$ (simply denies items below 3 cents [can be configured on config])

**Comment by ezraripps** [comment]
mhm i would suggest actually Looking through the readme, instead of telling people what to do. youve made so many issues for this, if you actually wanted to add something either wait or do it yourself.
