### ISSUE TITLE
Error getting prices

### ISSUE THREAD

**Issue by Flodkozza** [Arze1/CSGO-Overpay-Bot#17]
Error: null - Status Code: 401
Getting this error when it should get prices :(

**Comment by ezraripps** [comment]
What api key did u put in auth, should be the one specified in readme not the one from steam

**Comment by FreddyFish** [comment]
API key should be grabbed from here https://steamapi.io/user
Also stated in the readme.

**Comment by Flodkozza** [comment]
Oh god im so stupid man.. Thank you very much and sorry

**Comment by Flodkozza** [comment]
That's what happens when you don't read README.. lol

**Comment by ezraripps** [comment]
Lol yep. Would ask you to maybe never do that agian? Thanks :)

**Comment by Djolezor** [comment]
Yeah sure,I am so stupid..
