### ISSUE TITLE
JUNK TRADES

### ISSUE THREAD

**Issue by Monphito** [Arze1/CSGO-Overpay-Bot#23]
Ok so how do i make it so they can not trade junk to the bot

**Comment by Monphito** [comment]
when my friend overpays in junk skins it accetps

**Comment by Monphito** [comment]
i need it to decline

**Comment by ezraripps** [comment]
I am 99.9% sure there is option in config, if you would kindly read readme

**Comment by ezraripps** [comment]
And please dont make issues for EVERY SINGLE thing you want

**Comment by Monphito** [comment]
Well i did look at the config

**Comment by Monphito** [comment]
and i put a minimum i am not retarded i can see that. i have exhausted all options i see therefore i have some here to ask if i can get any help

**Comment by Monphito** [comment]
I saw the minimum price long before i put this up

**Comment by ezraripps** [comment]
Uhm just look through the code, really not that hard

**Comment by Monphito** [comment]
i have

**Comment by ezraripps** [comment]
Well what line/function could it be placed within

**Comment by Monphito** [comment]
let me test it with my friend one more time

**Comment by Monphito** [comment]
ok so i have a skin worth 1.02 and it accepted a offer with a bunch of bad skins

**Comment by Monphito** [comment]
my friend just tried it

**Comment by Monphito** [comment]
And what do you mean by "Well what line/function could it be placed within"

**Comment by FreddyFish** [comment]
If you want something made, then make it yourself. Help the community out. Please remember that this is not your custom coding service.

**Comment by Monphito** [comment]
I know
i messed up i thought minnum meant somehting else
