### ISSUE TITLE
[Question] Item price lista

### ISSUE THREAD

**Issue by Monphito** [Arze1/CSGO-Overpay-Bot#24]
how do you get the item price list

**Comment by Monphito** [comment]
What i mean is how did you do it and how did yo store it in the J SON because i am unaware of how you did it and i would like to have a crack at it

**Comment by ezraripps** [comment]
Jesus Christ, I will block you. ITS IN THE CODE, READ

**Comment by Monphito** [comment]
Lol nice threat

**Comment by Monphito** [comment]
do it no balls

**Comment by ezraripps** [comment]
> Lol nice threat

> do it no balls

just cuz u said that, blocked
