### ISSUE TITLE
Windows script error

### ISSUE THREAD

**Issue by ghost** [Arze1/CSGO-Overpay-Bot#29]
When i execute the java script file after entering all the needed data into the config file, It displays a error message saying that "Line: 5" / "Char: 1" has encountered a "Syntax error" (Microsoft J Script compilation error). If you have a fix for this issue it would be much appreciated.

**Comment by FreddyFish** [comment]
How do you run the script?

**Comment by ezraripps** [comment]
@FreddyFish he probably just opened it normally, please read readme

> node bot.js

o wow let me just open it normally

**Comment by FreddyFish** [comment]
Yeah that's what i thought as well. :P

Yeah, run the script using node bot.js
If the command is not found install the latest version of node: https://nodejs.org/en/

**Comment by ezraripps** [comment]
Solved
