### ISSUE TITLE
Trading not working?

### ISSUE THREAD

**Issue by LELManiac** [Arze1/CSGO-Overpay-Bot#30]
I am trying to test the bot before actually hosting it 24/7. The chat responses work fine, but the trading part won't work at all. Installed all like in the Readme file.
Also when logging in the following appears:

Logged into Steam as [something :3]
Error: Access Denied
    at SteamCommunity.<anonymous> (D:\Steam Bots\CSGO-Overpay-Bot\CSGO-Overpay-B
ot-master\node_modules\steamcommunity\components\webapi.js:15:20)
    at Request._callback (D:\Steam Bots\CSGO-Overpay-Bot\CSGO-Overpay-Bot-master
\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (D:\Steam Bots\CSGO-Overpay-Bot\CSGO-Overpay-Bot-ma
ster\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (D:\Steam Bots\CSGO-Overpay-Bot\CSGO-Overpay-Bot-mast
er\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at Gunzip.<anonymous> (D:\Steam Bots\CSGO-Overpay-Bot\CSGO-Overpay-Bot-maste
r\node_modules\request\request.js:1001:12)
    at Object.onceWrapper (events.js:291:19)

**Comment by LELManiac** [comment]
I also tried "reversing" back to the original version, without my little modifications in the code but still with the sharedSecret,identitySecret,username,password and api key. It still didn't work. And it might be worth pointing out that the account is limited.

**Comment by w3bb0** [comment]
It's not the steam API key

On 27 Feb 2017 5:10 pm, "LELManiac" <notifications@github.com> wrote:

I also tried "reversing" back to the original version, without my little
modifications in the code but still with the
sharedSecret,identitySecret,username,password
and api key. It still didn't work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Arze1/CSGO-Overpay-Bot/issues/30#issuecomment-282784445>,
or mute the thread

**Comment by LELManiac** [comment]
You mean the api key from steamapi.io? Because it certainly is the correct one

**Comment by FreddyFish** [comment]
Logged into Steam as [something :3]
Error: Access Denied

Seems like it's because your account is limited. Or you are blocked from logging into steam.

**Comment by LELManiac** [comment]
Seems like it's the limited account. Switched the config another account that is not limited and it works. Altought im working on a "working version" that does not have problems with the trades. Everything except the "outsider" trades works.

**Comment by LELManiac** [comment]
Well then i guess i can close this now. FIX: deposit $5
