### ISSUE TITLE
Auto-accept work towards fix

### ISSUE THREAD

**Issue by LELManiac** [Arze1/CSGO-Overpay-Bot#32]
The bot just auto-accepts every trade that is thrown at it. I tried modifying the code but I can't seem to figure out why it doesn't work... yet.
This is a part of my version: (from line 112)

if (isInArray(partnerid, config.adminIDs)) {
		client.chatMessage(partnerid, config.options.chatResponse.adminTrade);
		acceptOffer(offer);

	} else if (!offer.itemsToGive.length) {
		console.log(`${partnerid} just donated us items.`);

		client.chatMessage(partnerid, config.options.chatResponse.donation); //Sending message for donations
		acceptOffer(offer);

	} else if (priceItemsInOffer(offer.itemsToReceive) < config.options.minimumprice) {
		client.chatMessage(partnerid, config.options.chatResponse.junk); //Sending message for too cheap
		declineOffer(offer);

	} else if (priceItemsInOffer(offer.itemsToGive) > priceItemsInOffer(offer.itemsToReceive) * config.options.percentamount) {
		client.chatMessage(partnerid, config.options.chatResponse.tradeDeclined); //Sending message when trade declined
		declineOffer(offer);
		console.log(partnerid + "'s trade offer was declined."); //Notification for declined trade
		
	} else if (priceItemsInOffer(offer.itemsToGive) < priceItemsInOffer(offer.itemsToReceive) * config.options.percentamount) {
		client.chatMessage(partnerid, config.options.chatResponse.tradeAccepted); //Sending message for accepting offer
		acceptOffer(offer);
		console.log(partnerid + "'s trade offer was accepted."); //Notification for accepted trade
		
	}
});

and you can check the default by yourself, again from line 112.
Perhaps we should try and fix this? :+1: 

If ya ask me i think it's this part that doesn't "trigger" the rest:
 if (priceItemsInOffer(offer.itemsToGive) < priceItemsInOffer(offer.itemsToReceive) * config.options.percentamount)

**Comment by LELManiac** [comment]
With my version i think it actually completely skips the parts, exception being the admin auto-accept. Seems to go straight to the else statement and every trade request that isn't from an admin doesn't get an answer.

**Comment by w3bb0** [comment]
It works fine for most

**Comment by LELManiac** [comment]
Well for me it just autoaccepts everything... could you send me a code of yours, if you did modify it?

**Comment by LELManiac** [comment]
Seems like itemsToReceive and itemsToGive aren't defined..

**Comment by FreddyFish** [comment]
If you modified your code it's hard to help you. I dont think this issue section should be used for that. I would like to see this being used on the actual files in the repo.

**Comment by FreddyFish** [comment]
And it also works for me without problems.

**Comment by LELManiac** [comment]
Reversing for the 3rd time to original... lets see if it works now

**Comment by LELManiac** [comment]
And again it just auto-accepts everything. Can somebody send me a good version? Like if for everyone else works, could just someone send me their version? Of course, excluding the login info. Please.

**Comment by w3bb0** [comment]
just use the official one

**Comment by LELManiac** [comment]
I AM using the official one. The modded version was just a lil test. The official one only has more commands put into it, but the problem is that every trade is accepted, regardless of the offer values.

**Comment by LELManiac** [comment]
O shit i think i know why that doesn't work as intended. When writing the prices.json file it puts the price values in strings, such as "Souvenir AWP | Pit Viper (Well-Worn)":"51.68" and so the calculations don't work well. Anyway to solve that?

**Comment by LELManiac** [comment]
Also it looks like sending an offer in which the bot doesn't receive anything actually crashes it...

**Comment by ezraripps** [comment]
I have fixed glitch
