### ISSUE TITLE
my last issue got closed when i tried the thing he wrote it didnt work

### ISSUE THREAD

**Issue by eaxxoi** [Arze1/CSGO-Overpay-Bot#37]
so i had the unknown token const problem then i used cd desktop then cd bot then npm install. After that i am still getting the same exact error 
C:\Users\Liam\Desktop\bot>node bot.js
C:\Users\Liam\Desktop\bot\bot.js:33
const priceUrl = 'https://api.steamapi.io/market/prices/'+config.options.appid+'?    ^^^^^key='+config.options.apikey;

SyntaxError: Unexpected token const

**Comment by FreddyFish** [comment]
I'm not sure what you are doing wrong, but you should probably not be running this script if you have no idea of what you are doing.

1. Uninstall node.
2. Delete your bot folder.
3. Clone the repo
4. Setup your config.json
5. Install the LTS version of node (6.10.1)
6. If on windows (Shift + Right click in the folder where bot.js is located, and click "Open command window here"
-- Below should be typed into the command window --
7. npm install
8. node bot.js
-- End of command window --
9. IF errors (Post a full screenshot of your command window)

**Comment by eaxxoi** [comment]
cant do number 6 im on windows 10

**Comment by FreddyFish** [comment]
Yes you can. I'm on my windows 10 VM right now, and it's possible.
Edit: https://gyazo.com/4f2fe4c9fdc214d2b316103c448a71f3

**Comment by eaxxoi** [comment]
i press shift and right click and nothing happens at all

**Comment by FreddyFish** [comment]
Then CD to the folder instead, should be the same.

**Comment by eaxxoi** [comment]
i think my problem lies here :
twoFactorCode: SteamTotp.generateAuthCode(buffer.from(config.sharedSecret)
)

/*
	Getting prices
*/
const priceUrl

**Comment by FreddyFish** [comment]
Screenshot your command window.

**Comment by eaxxoi** [comment]
| +-- lodash.pick@4.4.0
  | +-- lodash.reduce@4.6.0
  | +-- lodash.reject@4.6.0
  | `-- lodash.some@4.6.0
  +-- node-bignumber@1.2.1
  `-- xml2js@0.4.17
    +-- sax@1.2.2
    `-- xmlbuilder@4.2.1

npm WARN arze-overpay-bot@1.0.0 No repository field.

C:\Users\Liam\Desktop\bot>node bot.js
C:\Users\Liam\Desktop\bot\bot.js:32
const priceUrl = 'https://api.steamapi.io/market/prices/'+config.options.appid+'?key='+config.options.apikey;
^^^^^
SyntaxError: Unexpected token const
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

C:\Users\Liam\Desktop\bot>

**Comment by FreddyFish** [comment]
It works on my end, so you are doing something wrong.

**Comment by eaxxoi** [comment]
im doing exactly as you instructed

**Comment by eaxxoi** [comment]
can you send me your bot.js in documents?

**Comment by FreddyFish** [comment]
I have the latest bot.js from the repo. Get that.
You are doing something wrong, or your PC is fucked. 

Try running it on a VM.

**Comment by eaxxoi** [comment]
i also have the newest bot but my script is probually fucked

**Comment by eaxxoi** [comment]
it says it wants a } intead of const but i cant have a }

**Comment by eaxxoi** [comment]
ok i think i kind off fixed it but now it says 
C:\Users\Liam\Desktop\bot>node bot.js
C:\Users\Liam\Desktop\bot\bot.js:26
        twoFactorCode: SteamTotp.generateAuthCode(buffer.from(config.sharedSecret))
                                                                                         ^

ReferenceError: buffer is not defined

**Comment by NLDoA** [comment]
If you are legit just trying to use the bot with NO experience beforehand, you probably won't get it to work for a while. You can't just expect to download the script and magically start making tons of money on your steam account lol. It takes time.

**Comment by eaxxoi** [comment]
well im trying to learn and i started with this project

**Comment by FreddyFish** [comment]
Did you set up your config.json with shared secret, username, password etc.?

**Comment by eaxxoi** [comment]
yes

**Comment by ezraripps** [comment]
Lol redownload it AND DONT CHANGE till u run it

**Comment by w3bb0** [comment]
yeah

**Comment by eaxxoi** [comment]
oh...

**Comment by eaxxoi** [comment]
now i get status code 401

**Comment by FreddyFish** [comment]
Sorry, but you are an idiot. 
You didnt edit the config.js

**Comment by eaxxoi** [comment]
yes i did idiot

**Comment by FreddyFish** [comment]
You did not do it correctly then.
The API key provided is invalid.

**Comment by eaxxoi** [comment]
but it doesnt update when i change the config it still keeps saying im signed in to a random account and gives me the 401 error

**Comment by eaxxoi** [comment]
ok

**Comment by eaxxoi** [comment]
its not the api key its from the site i was told to get it from

**Comment by eaxxoi** [comment]
i got the api key from steamapi.io

**Comment by FreddyFish** [comment]
You are not in the right folder then.

**Comment by eaxxoi** [comment]
GAIIOUS
API Key:
712c888428188d86a93f9ce0381f2f67  Generate
Plan:
DEV
Req/day:
5 000
Req/min:
50
Expires:
27.04.2017 23:59:59 Extend
Requests today:
0
Remaining today:
5 000

**Comment by eaxxoi** [comment]
that is my api isnt it ?

**Comment by FreddyFish** [comment]
Yes it is.

**Comment by eaxxoi** [comment]
well... i am using it but i still get the 401 error

**Comment by FreddyFish** [comment]
You are in the wrong dir then.

**Comment by eaxxoi** [comment]
im in the right one 
im in cd

**Comment by ezraripps** [comment]
What directory are u in

**Comment by FreddyFish** [comment]
"Im in cd"
oh god..

**Comment by kevdah** [comment]
lmao

**Comment by NLDoA** [comment]
@eaxxoi seriously, just learn how to actually program, and all the problems you have had so far would be easy fixes.

**Comment by NLDoA** [comment]
You aren't learning anything from this.

**Comment by ezraripps** [comment]
Uhm I think we figured it out
