### ISSUE TITLE
Error in confirmations

### ISSUE THREAD

**Issue by ghost** [Arze1/CSGO-Overpay-Bot#38]
Whenever I launch your bots, the codes goes fine without error.
However when I send offers, the confirmations page is always saying "you've  made too many requests recently. Please wait and try your request later". When I turn your script back off it turns fine again

**Comment by FreddyFish** [comment]
Change your confirmationInterval, in config.json


`"confirmationInterval": 30,`

**Comment by ghost** [comment]
I have changed it to 300, however same problem occured

**Comment by FreddyFish** [comment]
Are you sure about that?
Are you running this on a VPS?

**Comment by ghost** [comment]
I am trying to run it on my windows 10

**Comment by FreddyFish** [comment]
Weird, and you are not running any programs that checks frequently for confirmations? (Steam desktop auth, etc.?)

**Comment by ghost** [comment]
Ah I am indeed running SDA, thought I needed that.

**Comment by FreddyFish** [comment]
That could be the problem, as it checks for confirmations as well.
Try to exit SDA and test after a few minutes, and then start your bot to see if it makes any diffrence.

**Comment by ghost** [comment]
I will test it out as soon as I get home. Thanks

**Comment by ezraripps** [comment]
closed, too long w/o update
