### ISSUE TITLE
Bot accepting trades in which it will lose money

### ISSUE THREAD

**Issue by kevdah** [Arze1/CSGO-Overpay-Bot#41]
The bot is for some reason accepting trades that it isn't supposed to be accepting.
Screenshot: http://prntscr.com/etc4x7

Options:
 "minimumprice": 0.50,
    "acceptRandomFriendRequests": true,
    "priceRefreshInterval": 60,
    "confirmationInterval": 10,
    "percentamount": 0.93,

**Comment by kevdah** [comment]
Another screenshot, I tested the bot and I was able to get 10€ worth of skins by trading a few cases worth 0.03 each
http://prntscr.com/etcbgh

**Comment by kevdah** [comment]
Snippet from my bot.js https://hastebin.com/dunukawuzi.js

**Comment by FreddyFish** [comment]
I think this problem was actually fixed a few days ago.
Do you have the latest code?

**Comment by kevdah** [comment]
I might not, my code is about 15 days old.
Thanks, I will try cloning the new code.

**Comment by FreddyFish** [comment]
Yeah, latest update should fix your issue.

**Comment by kevdah** [comment]
Works flawlessly, thanks for the support Freddy, and I apologize for my stupidity. Closing this.

**Comment by w3bb0** [comment]
What's happend you re opened

**Comment by kevdah** [comment]
I went to bed after I updated the code, for some reason the bot accepted this trade http://prntscr.com/etgv7w
But the bot didn't accept these trades: http://prntscr.com/etgvui

**Comment by w3bb0** [comment]
I will take a look for u

**Comment by w3bb0** [comment]
Give me a few hours it's 8am here lol I'll look in a bit for you sorry

**Comment by kevdah** [comment]
Okay, here is my config:
    "minimumprice": 0.30,
    "acceptRandomFriendRequests": true,
    "priceRefreshInterval": 50,
    "confirmationInterval": 10,
    "percentamount": 0.93,
	"minPricePerItem": 0.10,

**Comment by FreddyFish** [comment]
Ohh.. That's weird.

**Comment by ezraripps** [comment]
Maybe your prices.json file is messed up, have you entered your api key for
steamapi.io in config?

**Comment by kevdah** [comment]
Yes, and it is updating regularily

**Comment by FreddyFish** [comment]
Really weird. Have you modified the code in any way? /

**Comment by ezraripps** [comment]
And do you see anything special in console?

**Comment by kevdah** [comment]
I have not modified the code after downloading the new code, I do get a lot of "error 439" or "error 339" (some kind of error keeps appearing)

**Comment by ezraripps** [comment]
Yes , what api key did you put in the config?

**Comment by kevdah** [comment]
The one that's available here https://steamapi.io/user

**Comment by ezraripps** [comment]
Ok, just checking because allot of ppl use the steam web api one

**Comment by kevdah** [comment]
Here's the error I'm getting http://prntscr.com/etlcnx

**Comment by ezraripps** [comment]
That is with getting prices, what is your price refresh rate at

**Comment by kevdah** [comment]
"priceRefreshInterval": 50,

**Comment by ezraripps** [comment]
Are you sure you put right api key with no spaces and such?

**Comment by kevdah** [comment]
"apikey":"9517fxxxxxxaa6xxxx0a4dfxe3xxxxxx",
Looks like that (I've censored some parts of it), no spaces and a comma after the "

**Comment by ezraripps** [comment]
Ok, just go to steamapi.io and make sure it's right key, 429 means it was
denied I'm pretty sure

**Comment by kevdah** [comment]
It is correct, I've increased the refresh rate to 150 now

**Comment by ezraripps** [comment]
Ok, does the error code less often or is it at the same rate

**Comment by kevdah** [comment]
Less frequently. 
Something that I noticed now is that the bot says "Got API key:" and then it's another key that I haven't entered as my API key in config, is this normal? http://prntscr.com/etlk5m

**Comment by ezraripps** [comment]
Yes, that is the steam api key not steamapi.io

**Comment by yaneony** [comment]
Due small bug in our system and initial users import, some users shared this key, so this is why you got 429 error. Please visit https://steamapi.io and get your new regenerated key. That should work.

This can be closed.

**Comment by ezraripps** [comment]
@jsieler seems to fix
