### ISSUE TITLE
can't run bot?

### ISSUE THREAD

**Issue by onziie** [Arze1/CSGO-Overpay-Bot#43]

**Comment by onziie** [comment]
it only gives me this error https://gyazo.com/c3a32d21c6b924cfb286161d2025d549

**Comment by onziie** [comment]
or this https://gyazo.com/db961318727aaafcc0ee89a44949fcdb

**Comment by daniel-box** [comment]
Hi, can you give a preview of your config file? Just blur out all your personal info (password etc)

**Comment by onziie** [comment]
https://gyazo.com/31e2ece4f7d9800e9db9d0e62e74f0b7

**Comment by onziie** [comment]
So i got some help but now a new error comes up https://gyazo.com/7d8cb6fa63164c494e327c0c50f4539f

**Comment by ezraripps** [comment]
Did u enter your shared secret and identity secret?

**Comment by onziie** [comment]
yup, https://gyazo.com/eeacdc896ff2f0bbea4842ac4127b519
fixed the problem at the buttom where it wasnt an , after the i wont give you free skins,

**Comment by daniel-box** [comment]
I see it.  Try putting a comma after that line. "blah blah.....m8" <--- add it there... Make it look like this -> "blah blah..... m8", 

The comma also screwed me over. Just remember, the last line under the commad{} shouldnt have a comma, just the ones that go first. Try it again.

**Comment by daniel-box** [comment]
LOOL, i guess it worked
