### ISSUE TITLE
when i run the bot i get this error

### ISSUE THREAD

**Issue by Silenttttttt** [Arze1/CSGO-Overpay-Bot#47]
if (error || response.statusCode !== 200) return console.log(`Error: ${error} - Status Code: ${response.statusCode}`);
                                                                                                                       ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request [as _callback] (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\bot.js:37:106)
    at self.callback (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\Muni\Desktop\CSGO-Overpay-Bot-master\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7

**Comment by Silenttttttt** [comment]
it works but why? and this error too Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401

**Comment by FreddyFish** [comment]
Are you sure the provided API key is correct?

If yes:
Where did you get the API key?

**Comment by Silenttttttt** [comment]
yea the bot is working but he always crash when i get that error

**Comment by Silenttttttt** [comment]
lol the api key was wrong but i got it on that site why it was wrongggg???? lollll

**Comment by Silenttttttt** [comment]
but i get the same error
undefined
Error: null - Status Code: 401
undefined
undefined
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401
undefined
undefined
Error: null - Status Code: 401
undefined
undefined
Error: null - Status Code: 401
undefined
undefined
Error: null - Status Code: 401
undefined
Error: null - Status Code: 401
Error: null - Status Code: 401
Error: null - Status Code: 401

**Comment by Silenttttttt** [comment]
Error: null - Status Code: 401

**Comment by FreddyFish** [comment]
You did not answer my question. 
Stop spamming the issue with multiple comments.

Where are you getting the API key?

**Comment by Silenttttttt** [comment]
you edited the message lol

**Comment by Silenttttttt** [comment]
https://steamapi.io/

**Comment by FreddyFish** [comment]
Pretty sure the API key provided is bad. 
Please generate a new one on steamapi.io

And tell me what happends if you go directly to the endpoint.

**Comment by Silenttttttt** [comment]
ok

**Comment by imran-099** [comment]
its not problem of steamapi.io key its problem of steam web api http://steamcommunity.com/dev/apikey
the bot will not work if your account is limited

**Comment by ezraripps** [comment]
You need to add 5$ and not have any other market restrictions

**Comment by FreddyFish** [comment]
I thought restricted account would give the Access denied error?  Or am i completely wrong here?

**Comment by Silenttttttt** [comment]
its working now it was the api i changed it and it start working
