### ISSUE TITLE
Pricing Problem

### ISSUE THREAD

**Issue by imran-099** [Arze1/CSGO-Overpay-Bot#50]
Hi 
i have setup this trading bot it works fine but it have prices problem it accept lowball like example i put ak redline ft in the bot and i send him trade in which from my side 2 keys and from bot side ak redline ft and the bot accept which is a loss.Any help will be appreciated (sorry for bad english :) )

**Comment by FreddyFish** [comment]
Duplicate issue.

**Comment by imran-099** [comment]
you have any solution for that? I know its a duplicate but i cant see a proper fix for this. I have downloaded new files and make everything new again but the problem still exists

**Comment by imran-099** [comment]
guys please am waiting for a proper answer please

**Comment by FreddyFish** [comment]
Do you have the latest version of the source?
I'm not sure but this might have been fixed.

Go back to the other issues, and comment there. It's pretty pointless to create new issues for the same problem.

**Comment by imran-099** [comment]
i have download the new version yesterday and test it and it still didnt work thats why i created new issue

**Comment by imran-099** [comment]
Anyone here

**Comment by FabriceDelahaij** [comment]
Try to use API from opskins.com or csgo.im for prices.
