### ISSUE TITLE
Error: Unexpected token } in JSON at position 1291

### ISSUE THREAD

**Issue by ghost** [Arze1/CSGO-Overpay-Bot#55]
There isn't even this position on the line... so I dunno whats happened.

Someone else take a look.

https://imgur.com/a/NrxY6

Thanks and I hope someone can help....

**Comment by FreddyFish** [comment]
Download the latest config.json and try again.

**Comment by Atosito** [comment]
No comma needed in last string.
```
{[...]

"newFriend": "Hey m8 thanks for adding my bot",

      "unknownCommand": "Unknown command.",

      "adminTrade": "Hey admin im giving my items now"

}}}
```
