### ISSUE TITLE
It bans your ip

### ISSUE THREAD

**Issue by Bkmd100** [Arze1/CSGO-Overpay-Bot#56]
after 2 minutes of it running, you can no longer confirm stuff and you recive "you've made too many requests recently. please wait and try your request again later." until you change your ip. I tried changing the confirmation interval but It didnt help....

**Comment by ezraripps** [comment]
Where do you see this error

**Comment by FreddyFish** [comment]
Change this: "confirmationInterval": 30,
in config.

**Comment by ezraripps** [comment]
solved
