### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by ScheeK4** [Arze1/CSGO-Overpay-Bot#57]
Hey, so the bot was working for me, then I started to get ERROR 404 after 1 restart. It was working for around 1 day. 

I've googled what ERROR 404 means and it means it cannot log into the account. Everything is right, and it was working before, I'm not sure what's up with it.

**Comment by FreddyFish** [comment]
ERROR 404 is not that it cannot login. ERROR 404 is not found.
Is your API keys correct?

**Comment by ScheeK4** [comment]
Hey, thanks for the reply, I fixed it. I redid all the configs and files 4 times to fix it! :P
