### ISSUE TITLE
Bot accepts trades when he is the one overpaying

### ISSUE THREAD

**Issue by ScheeK4** [Arze1/CSGO-Overpay-Bot#58]
Hey, so I tested this out with my friend. He traded my bot $1 for a $20 skin and the bot accepted it, he also did $30 for $60 items, and much more. I'm not sure how to fix this my config values the user items at 85%

**Comment by ScheeK4** [comment]
I'm assuming you guys don't know how to fix this issue oh well

**Comment by ezraripps** [comment]
Oh too bad, maybe you can stop being annoying and do something for
yourself, too bad

**Comment by ScheeK4** [comment]
Hey, sorry for bothering you, just posting my issue on the issue tab that github provides for their users who create products for other users. My apologies.

**Comment by ScheeK4** [comment]
But thanks for your help, best of luck.
