### ISSUE TITLE
Unexpected Token error

### ISSUE THREAD

**Issue by Taipoe** [Arze1/CSGO-Overpay-Bot#61]
Hello, I have an error whenever I try to start up the bot with with node 
![steam bot](https://user-images.githubusercontent.com/30641575/28853513-f13521f4-76e5-11e7-8f0a-8fe67100b7fb.PNG)
I have read the other issue reports that relate to this but whatever I do it seems to not fix it. many thanks in advance

**Comment by Taipoe** [comment]
oh and I also get this 
![steam bot 1](https://user-images.githubusercontent.com/30641575/28853564-44e6bd9e-76e6-11e7-8519-af114405a8c3.PNG)

**Comment by incognitojam** [comment]
The shorthand `=>` for defining functions is part of ES6 and is not available by default in node.js. Read more [here](https://nodejs.org/en/docs/es6/).
