### ISSUE TITLE
Error: Null - Status Code:401

### ISSUE THREAD

**Issue by Kojixus** [Arze1/CSGO-Overpay-Bot#63]
I followed the steps it got to the Steam API Key: Then it started doing that error 
Any Idea of why? 
Thanks 
![18ec4539b0de44698804ec4b4661a3b6](https://user-images.githubusercontent.com/31379715/29746994-c4e93bca-8ab9-11e7-94b6-98968b24cd2f.png)

My Steam - http://steamcommunity.com/id/kojixus/

**Comment by ezraripps** [comment]
did you add 5$ or more to your account
