### ISSUE TITLE
(node:11856) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by RIPD** [Arze1/CSGO-Overpay-Bot#64]
(node:11856) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

I dont know whai is wrong but it keeps spaming it in the console like every 30 seconds.
![error](https://user-images.githubusercontent.com/32552415/31245905-11883672-aa0c-11e7-8b52-28714061a9b7.PNG)

**Comment by ezraripps** [comment]
It's fine

**Comment by RIPD** [comment]
ok ty
