### ISSUE TITLE
Error 401 & wrong API key

### ISSUE THREAD

**Issue by L0Y4L** [Arze1/CSGO-Overpay-Bot#67]
Hey Arze!
The Error 401 might be because my bot isnt tradable yet. (New Account so I have to wait 15 days after paying 5€) but the "Got API key:BC9A5A254D8786982BF24FFE01865241" is not my api code/key.
Is that supposed to happen? :)

**Comment by ezraripps** [comment]
that's ur steam API key, steamapi.io key is different

**Comment by L0Y4L** [comment]
So theres nothing wrong at all, right? And the Error is just because my account is not ready yet, right? :)

**Comment by ezraripps** [comment]
Yes

**Comment by L0Y4L** [comment]
Oh ups.. sorry, I ment Error 404... ^^ And thanks for your help! :)
![af](https://user-images.githubusercontent.com/32991599/32301655-22b4594a-bf5f-11e7-8cfc-2af192c7a263.png)

**Comment by ezraripps** [comment]
Same thing

**Comment by L0Y4L** [comment]
Okay, thanks mate! I really appreciate your help! :) 👍
