### ISSUE TITLE
Prices

### ISSUE THREAD

**Issue by L0Y4L** [Arze1/CSGO-Overpay-Bot#68]
Hey, sorry to open a new issue but are the prices up to date? And if yes, do they update automaticly? 
If they're not, am I allowed to use this instead? 
https://api.steamapi.io/market/prices/730?key=cbd129cb94720bfbddceda5ba696e08e&beautify=1
or the "real" version of it : 
https://api.steamapi.io/market/prices/730?key=cbd129cb94720bfbddceda5ba696e08e

**Comment by ezraripps** [comment]
There's no reason to use the first, just a bigger file, why

**Comment by L0Y4L** [comment]
Okay but what about your prices? Are they always updated or like weekly or should I use my link?

**Comment by ezraripps** [comment]
Every hour

**Comment by ezraripps** [comment]
And the ones here are same source
