### ISSUE TITLE
Windows script host

### ISSUE THREAD

**Issue by disuth** [Arze1/CSGO-Overpay-Bot#69]
![bez tytulu](https://user-images.githubusercontent.com/34100095/33382085-1428ae18-d520-11e7-81a9-ab8eab5556e0.png)
need help i want to start bot but i cant any resolutions?

**Comment by FreddyFish** [comment]
Start it in CMD or Windows power shell.
By using node bot.js

**Comment by disuth** [comment]
![nia](https://user-images.githubusercontent.com/34100095/33433538-4260e59a-d5dc-11e7-80dd-d485016c1aef.png)
i started i got this

**Comment by iDefineHD** [comment]
Install the node modules with npm install (name of package)

**Comment by disuth** [comment]
npm install steam-user ?

**Comment by ezraripps** [comment]
Just npm install

**Comment by disuth** [comment]
i turn on the bot and i got that 
he is idling game
i am not sure he is working 
![bez tytulu](https://user-images.githubusercontent.com/34100095/33445088-4b6cf76c-d5fc-11e7-86d5-28520d28e432.png)

**Comment by disuth** [comment]
its working thanks for help guys
