### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by ghost** [Arze1/CSGO-Overpay-Bot#70]
I did everything correctly i know this becuase it logged into steam. But after that it gives me an error that goes like this. [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated. im new to coding so i am unsure how to fix it. can i get some help??
  
This is the issue line: return callback(new Error("Access Denied"));
  (it is in the modules) The directory is: C:\Users\Warptarium\Desktop\bot\node_modules\steamcommunity\components

**Comment by FreddyFish** [comment]
No need to do anything about "[DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated." Just ignore it.

**Comment by ghost** [comment]
Really? How does that work?

**Comment by FreddyFish** [comment]
It does not matter. Just use the source and enjoy!

**Comment by ghost** [comment]
Thanks! (:

**Comment by ghost** [comment]
When i run the program the bot does not come online? is that because of the error?

**Comment by FreddyFish** [comment]
Probably wrong login info in config.

**Comment by ghost** [comment]
oh yeah i got it. Thanks. sorry for asking so much but what is this error mean and do exactly?
