### ISSUE TITLE
steamapi.io isn't free now :(

### ISSUE THREAD

**Issue by pukakuka** [Arze1/CSGO-Overpay-Bot#71]
Hello ! Is there any alternative option except steamapi.io ? Or is there some built in price refresher in the code ? Have no idea :/

**Comment by iDefineHD** [comment]
The code could be changed to other sources. But most have price manipulation problems when free.

**Comment by pukakuka** [comment]
If I can ask you , do you use steamapi.io or something else ?

**Comment by iDefineHD** [comment]
I don't personally use this script, i dont want to say the free source here as not sure allowed. So add my steam http://steamcommunity.com/id/iDefineHD/

**Comment by ezraripps** [comment]
Yeah, there are no free options anymore.
