### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by ahojkzkittz** [Arze1/CSGO-Overpay-Bot#72]
Every time I open the file It starts loading and after a while acess denied what should id o?

**Comment by ezraripps** [comment]
Do you have mobile auth added and 5$+ spent on the account

**Comment by ahojkzkittz** [comment]
Ah i didn't spend 5$ on the account is that a problem?

**Comment by ezraripps** [comment]
Yes

**Comment by ahojkzkittz** [comment]
And so If I deposit 5$ on the account will it work ?

**Comment by ezraripps** [comment]
And if you have had mobile auth for 14 days....

**Comment by ahojkzkittz** [comment]
I have mobile auth for over a month, If I reach level 1 Will the bot work correctly?

**Comment by FreddyFish** [comment]
5$, authenticator for at least 14 days, and no vac/game bans should do it.
