### ISSUE TITLE
SteamAPI.io no longer provides free services

### ISSUE THREAD

**Issue by DentFuse** [Arze1/CSGO-Overpay-Bot#74]
SteamAPI.io no longer provides free services, please update code accordingly and tell users so. Also please close issue anytime :)

**Comment by ezraripps** [comment]
Oh no, $5!

**Comment by DentFuse** [comment]
Yup, please add that in files and tell users that they need to buy a subscription to use the prices API, or else you'll be getting issues saying that bot won't start.

**Comment by ezraripps** [comment]
people can figure it out themselves, these bots make 0$ anyways
